## Summary stats

All models trained on NVidia RTX 3070 with 8GM VRAM (240 W running at 90% usage)


Datasets can be found on the github page (https://github.com/drwslv/ErdosReviewSentiment)

In [4]:
import pandas as pd

## All regions (all types)

Size:

- train 1,230,642 samples 
- val 263,709 samples
- test 263,709 samples
- 
Mean rating: 4.183

Distribution: 5 (58.7%), 4 (20.0%), 3 (9.26%), 2 (7.20%), 1 (4.76%)

LSTM
- train duration: 4 hrs 8 min
- accuracy (test): 98.11%
- f1 (test): 0.98132

Roberta
- train duration: 9 hrs
- accuracy (test): 89.06%
- f1 (test): 0.88166

## All regions 5 star

LSTM 
- train duration: 9 hr 5 min
- accuracy (test): 93.94%
- f1 (test): 0.94016

In [23]:
df_regions = pd.read_csv('./data/all-states-test.csv')
df_regions.head()

,rating,text,pnn,lstm-neg,lstm-mixed,lstm-pos,lstm-pred,roberta-neg,roberta-mixed,roberta-pos,roberta-pred
0,3,Great spot for people watching and water view....,1,4.074575e-06,9.999282e-01,0.000068,1,0.000368,0.011360,0.988272,2
1,4,"I like it, don't care what nobody says",2,6.367181e-05,4.661905e-06,0.999932,2,0.013001,0.109073,0.877926,2
2,4,Good chicken tenders,2,1.438271e-04,3.365712e-02,0.966199,2,0.001314,0.064498,0.934188,2
3,5,Love I'd the servers were amazing,2,2.736243e-07,3.806092e-07,0.999999,2,0.000589,0.003003,0.996408,2
4,4,Love the ambiance,2,1.164160e-06,1.234627e-05,0.999986,2,0.000629,0.004779,0.994592,2

## Midwest (all types)

Size: 
- train 1,600,000 samples
- val 400,000 samples
- test 400,000 samples

Mean rating: 4.140 (train)

Distribution: 5 (56.5%), 4 (21.1%), 3 (9.87%), 2 (7.50%), 1 (5.04%)

Roberta
- train duration: 9.5 hrs
- accuracy: 88.21%
- f1: 0.86976

Bert-base
- train duration: 20 hrs
- accuracy: 83.00%
- f1: 0.78945

Bidirectional LSTM (** I used a different learning rate scheduler for this training, which could account for the lack of accuracy compared to the "all regions" model)
- train duration: 2 hrs
- accuracy: 85.43%
- f1: 0.86750

In [24]:
df_all = pd.read_csv('./data/midwest/big-test-sampled.csv')
df_all.head()

,rating,text,type,pnn,bert - neg,bert - mixed,bert - pos,bert - pred,lstm - neg,lstm - mixed,lstm - pos,lstm - pred,roberta - neg,roberta - mixed,roberta - pos,roberta - pred
0,5,love the 200 happyhour 2pm till 5pm thn again ...,Takeout Restaurant,2,0.023186,0.035969,0.940845,2,0.005154,0.053283,0.941562,2,0.000500,0.004984,0.994515,2
1,4,the food is decent and the cheese curds are aw...,Restaurant,2,0.002463,0.012228,0.985310,2,0.010283,0.586117,0.403600,1,0.001421,0.032834,0.965745,2
2,4,very helpful,Restaurant,2,0.045130,0.085370,0.869500,2,0.010875,0.147983,0.841142,2,0.001792,0.022055,0.976153,2
3,5,we had the best dinner here great open spot th...,Asian restaurant,2,0.004572,0.016085,0.979342,2,0.000389,0.003394,0.996217,2,0.000106,0.001357,0.998536,2
4,5,my new fav,Restaurant,2,0.032889,0.035972,0.931139,2,0.053597,0.258251,0.688152,2,0.001298,0.007771,0.990931,2

## Thai restaurants
Sizes
- train 66,494 samples
- val 16,577 samples
- test 7,272 samples
  
Mean rating: 4.398 (train)

Distribution: 5 (65.8%), 4 (20.0%), 3 (6.69%), 2 (4.27%), 1 (3.33%)

Roberta
- train duration: 37 min
- accuracy: 91.79%
- f1: >0.9

Bert-base
- train duration: 3 hrs
- accuracy: 86.67%
- f1: 0.81714

Bidirectional LSTM
- train duration: 15 minutes
- accuracy: 91.05%
- f1: >0.9


** Interestingly, bert model learned to *never* predict neutral/mixed

** Something strange with the test df is causing errors in writing the probabilities

In [13]:
df_thai = pd.read_csv('./data/thai-test.csv')
df_thai.head()

,rating,text,pnn,lstm-neg,lstm-mixed,lstm-pos,lstm-pred,bert-neg,bert-mixed,bert-pos,bert-pred,roberta-neg,roberta-mixed,roberta-pos,roberta-pred
0,5,Highly recommended! Good food and service.,2,0.000652,0.003544,0.995804,2,0.022161,0.034850,0.942989,2,0.000143,0.001649,0.998208,2
1,5,Excellence. Every time. My only regret is the ...,2,0.000957,0.008405,0.990637,2,0.048450,0.027053,0.924497,2,0.076064,0.128215,0.795721,2
2,5,Over a hour wait on a Friday night and still 5...,2,0.000805,0.020384,0.978811,2,0.047122,0.043983,0.908895,2,0.000941,0.005765,0.993294,2
3,5,A little hole in the wall I found! It's my go ...,2,0.001335,0.612893,0.385772,1,0.201603,0.154658,0.643739,2,0.275129,0.265585,0.459286,2
4,5,Halal chicken is good on menu.,2,0.001496,0.004327,0.994177,2,0.009803,0.028463,0.961734,2,0.002927,0.075450,0.921623,2

## Vegetarian restaurants
(appears to have *a lot* of reviews of Taco Bells)


Sizes: 
- train 480,135 samples
- val 96,027 samples
- test 58,655 samples (989.5kB)

Mean rating: 3.802 (train)

Distribution: 5 (45.7%), 4 (21.0%), 3 (13.5%), 2 (12.5%), 1 (7.22%)

Roberta
- train duration: 2 hr 25 min
- accuracy: 83.69%
- f1: 0.82592

Bert-base
- train duration: ~ 12 hrs
- accuracy: 77.48% 
- f1: 0.73062

Bidirectional LSTM
- train duration: 3 hr 23 min 
- accuracy: 88.32%
- f1: 0.88769

In [14]:
df_veg = pd.read_csv('./data/veg-test.csv')
df_veg.head()

,rating,text,pnn,lstm-neg,lstm-mixed,lstm-pos,lstm-pred,roberta-neg,roberta-mixed,roberta-pos,roberta-pred,bert-neg,bert-mixed,bert-pos,bert-pred
0,5,Really good food. I would recommend the BLT.,2,0.000191,0.065677,0.934132,2,0.000591,0.008005,0.991403,2,0.036378,0.089517,0.874104,2
1,5,Love it,2,0.001472,0.034975,0.963553,2,0.003498,0.009959,0.986543,2,0.015457,0.017589,0.966954,2
2,5,Their food is always fresh and amazing.,2,0.000018,0.000607,0.999375,2,0.000255,0.004217,0.995528,2,0.003684,0.012754,0.983563,2
3,5,We eat here about once every two weeks and the...,2,0.000098,0.000555,0.999347,2,0.017518,0.083187,0.899295,2,0.153344,0.198355,0.648301,2
4,5,Great,2,0.014054,0.089928,0.896018,2,0.008188,0.036346,0.955466,2,0.051032,0.074190,0.874779,2

- Consider investigating the "most egregious differences" between the different models