## Summary stats

All models trained on NVidia RTX 3070 with 8GM VRAM 

Datasets can be found on the github page (https://github.com/drwslv/ErdosReviewSentiment), except for the big dataset which can be found at (https://drive.google.com/drive/folders/1ek-ITB2fmp1KtOBfQHJXKwFpQ-eqvUzU?usp=drive_link)

In [1]:
import pandas as pd

## All regions

Size:

- train 
- val 
- test 

Mean rating: 

Distribution: 

LSTM

- train duration: 4 hrs 8 min
- accuracy (test): 98.11%
- f1 (test): 0.98132

In [ ]:
df_regions = pd.read_csv('./data/

## Big dataset (all types)

Size: 
- train 1,600,000 samples
- val 400,000 samples
- test 400,000 samples

Mean rating: 4.140 (train)

Distribution: 5 (56.5%), 4 (21.1%), 3 (9.87%), 2 (7.50%), 1 (5.04%)

Roberta
- train duration: 9.5 hrs
- accuracy: 88.21%
- f1: 0.86976

Bert-base
- train duration: 20 hrs
- accuracy: 83.00%
- f1: 0.78945

Bidirectional LSTM
- train duration: 2 hrs
- accuracy: 85.43%
- f1: 0.86750

In [78]:
df_all = pd.read_csv('./data/midwest/big-test-sampled.csv')

In [100]:
# Do some analysis on what different models predict -- could be interesting
df_all.head()

,rating,text,type,pnn,bert - neg,bert - mixed,bert - pos,bert - pred,lstm - neg,lstm - mixed,lstm - pos,lstm - pred,roberta - neg,roberta - mixed,roberta - pos,roberta - pred
0,5,love the 200 happyhour 2pm till 5pm thn again ...,Takeout Restaurant,2,0.023186,0.035969,0.940845,2,0.005154,0.053283,0.941562,2,0.000500,0.004984,0.994515,2
1,4,the food is decent and the cheese curds are aw...,Restaurant,2,0.002463,0.012228,0.985310,2,0.010283,0.586117,0.403600,1,0.001421,0.032834,0.965745,2
2,4,very helpful,Restaurant,2,0.045130,0.085370,0.869500,2,0.010875,0.147983,0.841142,2,0.001792,0.022055,0.976153,2
3,5,we had the best dinner here great open spot th...,Asian restaurant,2,0.004572,0.016085,0.979342,2,0.000389,0.003394,0.996217,2,0.000106,0.001357,0.998536,2
4,5,my new fav,Restaurant,2,0.032889,0.035972,0.931139,2,0.053597,0.258251,0.688152,2,0.001298,0.007771,0.990931,2

## Thai restaurants
Sizes
- train 66,494 samples
- val 16,577 samples
- test 7,272 samples
  
Mean rating: 4.398 (train)

Distribution: 5 (65.8%), 4 (20.0%), 3 (6.69%), 2 (4.27%), 1 (3.33%)

Roberta
- train duration: 37 min
- accuracy: 91.79%
- f1: >0.9

Bert-base
- train duration: 3 hrs
- accuracy: 86.67%
- f1: 0.81714

Bidirectional LSTM
- train duration: 15 minutes
- accuracy: 91.05%
- f1: >0.9


** Interestingly, bert model learned to *never* predict neutral/mixed

** Something strange with the test df is causing errors in writing the probabilities

In [103]:
df_thai = pd.read_csv('./data/thai-test.csv')
df_thai.head()

,rating,text,pnn,lstm-neg,lstm-mixed,lstm-pos,lstm-pred,bert-neg,bert-mixed,bert-pos,bert-pred,roberta-neg,roberta-mixed,roberta-pos,roberta-pred
0,5,Highly recommended! Good food and service.,2,0.000652,0.003544,0.995804,2,0.022161,0.034850,0.942989,2,0.000143,0.001649,0.998208,2
1,5,Excellence. Every time. My only regret is the ...,2,0.000957,0.008405,0.990637,2,0.048450,0.027053,0.924497,2,0.076064,0.128215,0.795721,2
2,5,Over a hour wait on a Friday night and still 5...,2,0.000805,0.020384,0.978811,2,0.047122,0.043983,0.908895,2,0.000941,0.005765,0.993294,2
3,5,A little hole in the wall I found! It's my go ...,2,0.001335,0.612893,0.385772,1,0.201603,0.154658,0.643739,2,0.275129,0.265585,0.459286,2
4,5,Halal chicken is good on menu.,2,0.001496,0.004327,0.994177,2,0.009803,0.028463,0.961734,2,0.002927,0.075450,0.921623,2

## Vegetarian restaurants
Sizes: 
- train 480,135 samples
- val 96,027 samples
- test 58,655 samples (989.5kB)

Mean rating: 3.802 (train)

Distribution: 5 (45.7%), 4 (21.0%), 3 (13.5%), 2 (12.5%), 1 (7.22%)

Roberta
- train duration: 2 hr 25 min
- accuracy: 83.69%
- f1: 0.82592

Bert-base
- train duration: ~ 12 hrs
- accuracy: 77.48% 
- f1: 0.73062

Bidirectional LSTM
- train duration: 3 hr 23 min 
- accuracy: 88.32%
- f1: 0.88769

In [109]:
df_veg = pd.read_csv('./data/veg-test.csv')
df_veg.head()

,rating,text,pnn,lstm-neg,lstm-mixed,lstm-pos,lstm-pred,roberta-neg,roberta-mixed,roberta-pos,roberta-pred,bert-neg,bert-mixed,bert-pos,bert-pred
0,5,Really good food. I would recommend the BLT.,2,0.000191,0.065677,0.934132,2,0.000591,0.008005,0.991403,2,0.036378,0.089517,0.874104,2
1,5,Love it,2,0.001472,0.034975,0.963553,2,0.003498,0.009959,0.986543,2,0.015457,0.017589,0.966954,2
2,5,Their food is always fresh and amazing.,2,0.000018,0.000607,0.999375,2,0.000255,0.004217,0.995528,2,0.003684,0.012754,0.983563,2
3,5,We eat here about once every two weeks and the...,2,0.000098,0.000555,0.999347,2,0.017518,0.083187,0.899295,2,0.153344,0.198355,0.648301,2
4,5,Great,2,0.014054,0.089928,0.896018,2,0.008188,0.036346,0.955466,2,0.051032,0.074190,0.874779,2

In [70]:
df_veg[df_veg['lstm-pred'] != df_veg['roberta-pred']].sample(20)

,rating,text,pnn,lstm-neg,lstm-mixed,lstm-pos,lstm-pred,clean-text,roberta-neg,roberta-mixed,roberta-pos,roberta-pred
39204,4,Good ambiance..food is hygienic but tastes ave...,2,0.002174,0.970895,0.026931,1,good ambiancefood is hygienic but tastes avera...,0.061745,0.455215,0.483039,2
36823,4,"Service was great, Gail was on top of everythi...",2,0.017220,0.064379,0.918401,2,service was great gail was on top of everythin...,0.137809,0.431464,0.430727,1
46698,3,"Missing item, had to go inside to get it.",1,0.025730,0.950828,0.023442,1,missing item had to go inside to get it,0.711072,0.215077,0.073850,0
40780,3,Ordering is easier by choice,1,0.001316,0.979651,0.019034,1,ordering is easier by choice,0.040907,0.355741,0.603352,2
43876,3,Deleted the App. Doesn't work.,1,0.002364,0.995229,0.002407,1,deleted the app doesnt work,0.889053,0.092455,0.018492,0
33727,4,food is great. the restaurant however is not t...,2,0.003697,0.035671,0.960632,2,food is great the restaurant however is not th...,0.074438,0.629343,0.296219,1
12758,5,I was really shocked by how good this was. It ...,2,0.008996,0.953055,0.037949,1,i was really shocked by how good this was it w...,0.132980,0.235578,0.631441,2
40271,3,"Shouldn't come up under ""authentic"". It's Tex...",1,0.000794,0.899700,0.099506,1,shouldnt come up under authentic its texmex,0.688561,0.195022,0.116417,0
15572,5,I said it before but I'll say it again rice ha...,2,0.449899,0.483312,0.066789,1,i said it before but ill say it again rice has...,0.772058,0.174053,0.053889,0
36622,4,Burrito was good. Was pretty quick.,2,0.000930,0.784725,0.214346,1,burrito was good was pretty quick,0.001476,0.090498,0.908026,2
38515,4,Fast food,2,0.111177,0.705002,0.183821,1,fast food,0.021294,0.178665,0.800041,2
31514,4,"Pretty decent, cool take on sushi rolls.",2,0.001223,0.614522,0.384256,1,pretty decent cool take on sushi rolls,0.004707,0.244319,0.750974,2
40335,3,Messed up the order.,1,0.019957,0.961951,0.018092,1,messed up the order,0.649057,0.308268,0.042676,0
41618,3,Decent food. They're open late which is nice,1,0.007071,0.883558,0.109371,1,decent food theyre open late which is nice,0.006335,0.108473,0.885191,2
45853,3,It took a very long time to get just a burrito...,1,0.001609,0.995080,0.003311,1,it took a very long time to get just a burrito...,0.672385,0.249672,0.077942,0
55137,2,Now you have to use a Kiosk to order... My God...,0,0.009333,0.212462,0.778205,2,now you have to use a kiosk to order my god th...,0.903276,0.077141,0.019583,0
30212,4,"Food good, just wish they stil sold mexican pi...",2,0.000895,0.864831,0.134273,1,food good just wish they stil sold mexican pizza,0.021858,0.366678,0.611464,2
39609,3,Sad when you order a double crunch wrap and it...,1,0.002787,0.971103,0.026111,1,sad when you order a double crunch wrap and it...,0.529794,0.357373,0.112833,0
40500,3,Not the cleanest taco bell but the service was...,1,0.608051,0.306464,0.085484,0,not the cleanest taco bell but the service was...,0.016041,0.400930,0.583029,2
57082,2,(Translated by Google) Alful\n\n(Original)\nAlful,0,0.461395,0.269294,0.269311,0,alful original alful,0.061416,0.217787,0.720796,2