## Summary stats

All models trained on NVidia RTX 3070 with 8GM VRAM 

Datasets can be found on the github page (https://github.com/drwslv/ErdosReviewSentiment), except for the big dataset which can be found at (https://drive.google.com/drive/folders/1ek-ITB2fmp1KtOBfQHJXKwFpQ-eqvUzU?usp=drive_link)

In [1]:
import pandas as pd

## Big dataset (all types)

Size: 
- train 1,600,000 samples
- val 400,000 samples
- test 400,000 samples

Mean rating: 4.140 (train)

Distribution: 5 (56.5%), 4 (21.1%), 3 (9.87%), 2 (7.50%), 1 (5.04%)

Roberta
- train duration: 9.5 hrs
- accuracy: 88.21%
- f1: 0.86976

Bert-base
- train duration: 20 hrs
- accuracy: 83.00%
- f1: 0.78945

Bidirectional LSTM
- train duration: 2 hrs
- accuracy: 85.43%
- f1: 0.86750

In [16]:
df_all = pd.read_csv('./data/midwest/big-test-sampled.csv')

In [17]:
# Do some analysis on what different models predict -- could be interesting
df_all.head()

,rating,text,type,pnn,bert - probs,roberta - probs,Bidirectional LSTM - probs
0,5,love the 200 happyhour 2pm till 5pm thn again ...,Takeout Restaurant,2,[0.02318591 0.03596894 0.94084525],[5.0048920e-04 4.9842149e-03 9.9451524e-01],[0.00515424 0.05328341 0.94156235]
1,4,the food is decent and the cheese curds are aw...,Restaurant,2,[0.00246261 0.01222768 0.98530966],[0.00142059 0.03283421 0.9657452 ],[0.01028319 0.58611655 0.40360028]
2,4,very helpful,Restaurant,2,[0.04512969 0.08537012 0.86950016],[0.00179214 0.02205463 0.97615325],[0.01087487 0.14798339 0.8411417 ]
3,5,we had the best dinner here great open spot th...,Asian restaurant,2,[0.00457231 0.0160854 0.97934234],[1.06368854e-04 1.35732337e-03 9.98536229e-01],[3.8917517e-04 3.3940626e-03 9.9621671e-01]
4,5,my new fav,Restaurant,2,[0.03288918 0.03597173 0.9311391 ],[0.0012976 0.00777086 0.9909315 ],[0.05359737 0.2582511 0.68815154]

## Thai restaurants
Sizes
- train 66,494 samples
- val 16,577 samples
- test 7,272 samples
  
Mean rating: 4.398 (train)

Distribution: 5 (65.8%), 4 (20.0%), 3 (6.69%), 2 (4.27%), 1 (3.33%)

Roberta
- train duration: 37 min
- accuracy: 91.79%
- f1: >0.9

Bert-base
- train duration: 3 hrs
- accuracy: 86.67%
- f1: 0.81714

Bidirectional LSTM
- train duration: 15 minutes
- accuracy: 91.05%
- f1: >0.9


** Interestingly, bert model learned to *never* predict neutral/mixed

** Something strange with the test df is causing errors in writing the probabilities

In [11]:
df_thai = pd.read_csv('./data/thai-train.csv')
df_thai['rating'].value_counts(normalize=True)

rating
5    0.657759
4    0.200214
3    0.066923
1    0.042711
2    0.032394
Name: proportion, dtype: float64

## Vegetarian restaurants
Sizes: 
- train 480,135 samples
- val 96,027 samples
- test 58,655 samples (989.5kB)

Mean rating: 3.802 (train)

Distribution: 5 (45.7%), 4 (21.0%), 3 (13.5%), 2 (12.5%), 1 (7.22%)

Roberta
- train duration: 2 hr 25 min
- accuracy: 83.69%
- f1: 0.82592

Bert-base
- train duration
- accuracy
- f1

Bidirectional LSTM
- train duration: 3 hr 23 min 
- accuracy: 88.32%
- f1: 0.88769

In [66]:
df_veg = pd.read_csv('./data/veg-test.csv')

In [67]:
df_veg[(df_veg['pnn'] == 0) & (df_veg['lstm-pred'] == 2)].sample(20)

,rating,text,pnn,lstm-neg,lstm-mixed,lstm-pos,lstm-pred,clean-text,roberta-neg,roberta-mixed,roberta-pos,roberta-pred
57092,2,👎👎,0,0.188288,0.261354,0.550358,2,NaN,0.122519,0.185841,0.691640,2
53158,1,All I asked for was fresh cinabons and they ga...,0,0.003496,0.474303,0.522201,2,all i asked for was fresh cinabons and they ga...,0.413778,0.308941,0.277281,0
57238,2,If your into old ladies diarea for hamburger t...,0,0.000072,0.000273,0.999656,2,if your into old ladies diarea for hamburger t...,0.098626,0.169917,0.731456,2
47492,1,Shouldn't even give a star once again can't ge...,0,0.000370,0.001636,0.997994,2,shouldnt even give a star once again cant get ...,0.904739,0.083439,0.011822,0
56179,2,Yes,0,0.108051,0.206177,0.685772,2,yes,0.033409,0.130678,0.835914,2
54843,2,Of course a 20 year old and all his buddy run ...,0,0.001292,0.000141,0.998567,2,of course a 20 year old and all his buddy run ...,0.378637,0.253869,0.367494,0
55918,2,Cannot fathom paying those prices for grilled ...,0,0.000044,0.000483,0.999473,2,cannot fathom paying those prices for grilled ...,0.880928,0.063625,0.055447,0
57354,2,"I love the manager, the store is beautiful but...",0,0.000051,0.000249,0.999699,2,i love the manager the store is beautiful but ...,0.037050,0.072595,0.890355,2
58383,2,I was never at Taco Bell... I'm sorry I I can'...,0,0.022981,0.000151,0.976868,2,i was never at taco bell im sorry i i cant giv...,0.809586,0.143359,0.047055,0
54862,2,"Ask for names, can't spell or pronounce either...",0,0.191025,0.036173,0.772802,2,ask for names cant spell or pronounce either slow,0.600789,0.357078,0.042133,0
58361,2,Taco burrito kisses!,0,0.438058,0.063215,0.498727,2,taco burrito kisses,0.010930,0.088085,0.900985,2
52969,1,Good service . Miss the old menu!! Not much to...,0,0.000056,0.000594,0.999350,2,good service miss the old menu not much to ch...,0.024095,0.310327,0.665578,2
51099,1,I just lost every bit of time I had gained on ...,0,0.220015,0.002821,0.777164,2,i just lost every bit of time i had gained on ...,0.631539,0.211885,0.156576,0
58458,2,"Thought this was a Tako bell, I was wrong",0,0.001324,0.004789,0.993887,2,thought this was a tako bell i was wrong,0.327625,0.356520,0.315854,1
55678,2,Good food as always service was slow though.,0,0.006716,0.335861,0.657424,2,good food as always service was slow though,0.016425,0.265880,0.717695,2
50377,1,Drunk food,0,0.020843,0.300094,0.679063,2,drunk food,0.241886,0.296637,0.461477,2
55624,2,"Expensive, small portions and okay-ish servers...",0,0.059101,0.083466,0.857433,2,expensive small portions and okayish servers t...,0.001953,0.068758,0.929289,2
52743,1,"My food is never labeled, I have to guess whic...",0,0.074087,0.000576,0.925338,2,my food is never labeled i have to guess which...,0.809354,0.154517,0.036129,0
47877,1,Employees always seem to have their own little...,0,0.000090,0.001355,0.998555,2,employees always seem to have their own little...,0.100669,0.232120,0.667211,2
55008,2,Please make sure you get what you order. Servi...,0,0.397009,0.011497,0.591494,2,please make sure you get what you order servic...,0.062780,0.244203,0.693016,2