## Convert raw json to csv

In [2]:
import json
import pandas as pd

### Read-in 10-core file

In [3]:
df_core = pd.read_json('./data/review-Wyoming_10.json.gz', compression='gzip', lines=True, dtype={'text': 'str'})

In [ ]:
df_core.columns

Index(['user_id', 'name', 'time', 'rating', 'text', 'pics', 'resp', 'gmap_id'], dtype='object')

In [41]:
df_core = df_core[['gmap_id','rating','time','text']]

In [42]:
df_core.head(2)

,gmap_id,rating,time,text
0,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b,5,1602893531994,"When knowledge is key and kindness matters, Ni..."
1,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b,5,1575991509006,The entire team is outstanding! They are profe...

In [53]:
df_core = df_core[df_core['text']!='None']

In [54]:
df_core.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234655 entries, 0 to 427546
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   gmap_id  234655 non-null  object
 1   rating   234655 non-null  int64
 2   time     234655 non-null  int64
 3   text     234655 non-null  object
dtypes: int64(2), object(2)
memory usage: 9.0+ MB

### Read-in meta file

In [ ]:
df_meta = pd.read_json('./data/meta-Wyoming.json.gz', compression='gzip', lines=True)

In [35]:
df_meta.columns

Index(['name', 'address', 'gmap_id', 'description', 'latitude', 'longitude',
       'category', 'avg_rating', 'num_of_reviews', 'price', 'hours', 'MISC',
       'state', 'relative_results', 'url'],
      dtype='object')

In [36]:
df_meta = df_meta[['gmap_id','category','latitude','longitude']]

In [37]:
df_meta.head(2)

,gmap_id,category,latitude,longitude
0,0x875901dbacdf1fb7:0x5e0aea8e0909ba5c,[Electrician],42.823146,-108.718111
1,0x8758dd38d63c9017:0xe4bca45ee1b90b43,"[Chiropractor, Alternative medicine practition...",43.034454,-108.400955

In [45]:
df_meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12088 entries, 0 to 12087
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   gmap_id    12088 non-null  object
 1   category   12000 non-null  object
 2   latitude   12088 non-null  float64
 3   longitude  12088 non-null  float64
dtypes: float64(2), object(2)
memory usage: 377.9+ KB

### Merge

In [55]:
df = pd.merge(df_core, df_meta, how='left', on='gmap_id')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234871 entries, 0 to 234870
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   gmap_id    234871 non-null  object
 1   rating     234871 non-null  int64
 2   time       234871 non-null  int64
 3   text       234871 non-null  object
 4   category   234830 non-null  object
 5   latitude   234871 non-null  float64
 6   longitude  234871 non-null  float64
dtypes: float64(2), int64(2), object(3)
memory usage: 12.5+ MB

In [57]:
df

,gmap_id,rating,time,text,category,latitude,longitude
0,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b,5,1602893531994,"When knowledge is key and kindness matters, Ni...","[Real estate agency, Commercial real estate ag...",43.022906,-108.386042
1,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b,5,1602893531994,"When knowledge is key and kindness matters, Ni...","[Real estate agency, Commercial real estate ag...",43.022906,-108.386042
2,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b,5,1575991509006,The entire team is outstanding! They are profe...,"[Real estate agency, Commercial real estate ag...",43.022906,-108.386042
3,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b,5,1575991509006,The entire team is outstanding! They are profe...,"[Real estate agency, Commercial real estate ag...",43.022906,-108.386042
4,0x8758dd1bb1e7e151:0x3c36bd03d11f4222,5,1593125190987,They provided immediate and thorough help. I h...,"[Computer repair service, Computer consultant,...",43.024816,-108.388555
...,...,...,...,...,...,...,...
234866,0x53349429523d615b:0x2a66a9272032e8b4,5,1558556949602,(Translated by Google) She has gotten her clot...,"[Fast food restaurant, Breakfast restaurant, C...",44.281360,-105.493369
234867,0x53349429523d615b:0x2a66a9272032e8b4,5,1553379372975,(Translated by Google) Very good service 24 ho...,"[Fast food restaurant, Breakfast restaurant, C...",44.281360,-105.493369
234868,0x53349429523d615b:0x2a66a9272032e8b4,5,1602091528892,(Translated by Google) Fine\n\n(Original)\nДобре,"[Fast food restaurant, Breakfast restaurant, C...",44.281360,-105.493369
234869,0x53349429523d615b:0x2a66a9272032e8b4,5,1505342223010,(Translated by Google) I love there Carmel str...,"[Fast food restaurant, Breakfast restaurant, C...",44.281360,-105.493369
234870,0x53349429523d615b:0x2a66a9272032e8b4,1,1534356212894,(Translated by Google) no umus\n\n(Original)\n...,"[Fast food restaurant, Breakfast restaurant, C...",44.281360,-105.493369

In [ ]:
df.to_csv('./data/wyoming.csv', index=False)